### ISSUE TITLE
Include the ability to specify a version for each repo. 

### ISSUE THREAD

**Issue by Mike-Dunton** [GannettDigital/actions-library-builder#3]
Could we include the ability to specify the repo tag/branch. 

I was thinking something like 
```
      - name: Build Library
        uses: GannettDigital/actions-library-builder@main
        with: 
          repo_owner: GannettDigital
          repo_list: "my-repo-A@main,my-repo-B@v1.2.3,my-repo-C"
          repo_version: something-other-than-main
          private_action_token: ${{ secrets.PRIVATE_ACTION_TOKEN }}
```

I think a sane default for `repo_version` could be "main". You could just leave it off from the input or include it if you wanted something other than "main" by default.

The checkout process would only use "repo_version" if nothing was specified in the list of repos.
